services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --check-caps false --ISCAgent false
    restart: always
    ports:
      - '40022:22'  
      - '41773:1972'
      - '42773:52773'
      - '43773:53773'
    volumes:
      - ./:/irisdev/app
    environment:
      - PYTHONHOME=/usr

